### ISSUE TITLE
some irregular name makes error on loading

### ISSUE THREAD

**Issue by dominix** [romainmarcoux/malicious-domains#1]
irregular name use RAM for nothing and  leads to errors 
(I am not on fortinet)
ex:

grep '\.\.' /var/cache/malicious-domains/full-domains-ab.txt 
2s5wzb.mcgo2.com..e

dig 2s5wzb.mcgo2.com..e
dig: '2s5wzb.mcgo2.com..e' is not a legal name (empty label)

should set a filter on '..' or malformed domain name.
regards.

**Comment by romainmarcoux** [comment]
Thank you for your issue.
The issue has been solved for several months.
